# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.IntegerField(max_length=11)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=10, verbose_name='Nº')),
                ('complemento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Divida ativa'), ('Inativo', 'Divida inativa')], max_length=16)),
                ('equipamento', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=5)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('Serial', models.CharField(blank=True, max_length=100, null=True)),
                ('parimonio', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provedor')),
            ],
        ),
    ]
